--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  ayami_muto
name_ja: あやみ
name_en: Ayami
catchphrase: 頑張り屋さん。いつも全力のリーダー天使！
hobby: サッカー観戦
worry: みんなのネット接続速度が心配
favorite_subject: 体育

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  ayaka_miyoshi
name_ja: あやか
name_en: Ayaka
catchphrase: みんなのお姉さん的存在。クール天使！
hobby: 香水集め
worry: クールでちょっととっつきにくいと言われる
favorite_subject: 飛行演習

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  airi_matsui
name_ja: あいり
name_en: Airi
catchphrase: 不器用な愛され天使！
hobby: 水泳
worry: 人前で緊張してしまうこと
favorite_subject: 飛行演習

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  suzuka_nakamoto
name_ja: すずか
name_en: Suzuka
catchphrase: 自分を持ったパワフル天使！
hobby: ダンス、歌
worry: 家で歌うと怒られること
favorite_subject: 合唱
emoticon: (ﾟ∇^*)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  marina_horiuchi
name_ja: まりな
name_en: Marina
catchphrase: ファンタジーを愛する不思議天使！
hobby: 歌、ピアノ
worry: 虹が出たら飛ぶのがこわい
favorite_subject: 音楽
emoticon: (･ｪ･∪)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  raura_iida
name_ja: らうら
name_en: Raura
catchphrase: 元気いっぱいボーイッシュ天使！
hobby: サックス演奏
worry: 筋肉がついてきたこと
favorite_subject: 音楽
emoticon: (o´▽`)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  nene_sugisaki
name_ja: ねね
name_en: Nene
catchphrase: 食べるの大好き、コミカル天使！
hobby: おいしいものを食べる
worry: お腹いっぱい食べるとうまく飛べないこと
favorite_subject: 家庭科
emoticon: (｡-ω･)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  hinata_sato
name_ja: ひなた
name_en: Hinata
catchphrase: 楽しいこと大好きなオテンバ天使！
hobby: 折り紙
worry: 寝たら勉強したことを忘れてしまうこと
favorite_subject: 美術
emoticon: (´∀｀)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  yui_mizuno
name_ja: ゆい
name_en: Yui
catchphrase: ダンスが売りのあまえんぼ天使！
hobby: ダンス
worry: 空を飛ぶので、日焼けが気になる
favorite_subject: 体育
emoticon: (｡･д･｡)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  moa_kikuchi
name_ja: もあ
name_en: Moa
catchphrase: マイペースののんびり屋さん天使！
hobby: スポーツ
worry: 空を飛ぶと置いてきぼりになる
favorite_subject: 飛行演習
emoticon: (〃^∇^)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  hana_taguchi
name_ja: はな
name_en: Hana
catchphrase: 自分を持ったしっかり者天使！
hobby: 体を動かすこと
worry: 一人前の天使になったら、髪の毛がくりんくりんにならないか心配
favorite_subject: 体育
emoticon: (*･ω･)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  rinon_isono
name_ja: りのん
name_en: Rinon
catchphrase: 我道を行く、フリーダム天使！
hobby: ファッション
worry: 天使の服装の種類が少ないこと
favorite_subject: 家庭科
emoticon: (｡･ｗ･｡)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  yunano_notsu
name_ja: ゆなの
name_en: Yunano
catchphrase: 前向きにがんばる！ポジティブ天使！
hobby: 犬と遊ぶこと、おしゃべり
worry: 特にありません！
favorite_subject: 数学
emoticon: (^∇^)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  mariri_sugimoto
name_ja: まりり
name_en: Mariri
catchphrase: 流行りもの大好きオシャレ天使！
hobby: なんでもデコること
worry: 忙しくなってきてゆっくりお買い物にいけない
favorite_subject: 美術、家庭科
emoticon: (ゝω･)

--- !ruby/object:SakuraGakuin::Angel
id: !ruby/sym
  saki_ooga
name_ja: さき
name_en: Saki
catchphrase: 勉強熱心、文化系天使！
hobby: 色んなお菓子を食べること
worry: よく道に迷う
favorite_subject: 国語
emoticon: (*ﾟ▽ﾟ)
